### PR TITLE
Create Ticket was broken for JIRA version >= 9.x

### PR DESCRIPTION
**Pull request by bdeyal**
See here:
https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html

The change checks if we have server version >= 9.x and if so, calls the new API for issuetypes list.

### CODE REVIEW

**Comment by frimicc** [comment]
Thanks for fixing this, this looks great. 

@bdeyal How would you like your name and email mentioned in the Contributors section of the docs?

**Comment by bdeyal** [comment]
@frimicc  I guess as everybody else (name + email) can be taken from commit. Thanks!

**Comment by msven** [comment]
@frimicc Is this ready to merge or is there anything blocking it?

**Comment by bdeyal** [comment]
Nothing blocking. We are using it for some time now without problems. Thanks!

**Comment by frimicc** [comment]
I'm looking for a new maintainer for this project, if either @bdeyal or @msven are interested.

**Pull request merged**
