### PR TITLE
allow other ways of authorization besides basic username/password auth

### PR DESCRIPTION
**Pull request by zhouzhen1**
In my workplace we do not use username/password to access our JIRA instance. We use some token-based approach for authorization. I created this path so that it's not must to use username/password. Together with the module's feature of exposing UA, it allows flexible authorization scenarios.

### CODE REVIEW

**Comment by frimicc** [comment]
I wish I had a way to test this in the automated unit test... 

Can you update the unit test (https://github.com/frimicc/jira-client-automated/blob/master/t/jira-client-automated.t) to allow for this case, run it in your environment, and resubmit? Right now the test script won't run if you don't specify username and password too. 

Thanks!

**Comment by zhouzhen1** [comment]
I cannot really update the test, as it's a little bit special for our company. We use SiteMinder auth on our Jira instances. When connection Jira, it's like, 

1. my $jira = JIRA::Client::Automated->new($url);
2. get SiteMinder cookie by Kerberos token. 
3. my $ua = $jira->ua();
4. $ua->cookie_jar = $cookie_jar_from_step2;
5. Jira work with $jira. 

In the Kerberos to SiteMinder cookie_jar step there involves something custom setups in our company, as well as some internally developed Perl module. And I cannot disclose it here. 

But I guess there are other companies or users that do not use username/passwd auth. So if JIRA::Client::Automated has the option for user to not use username/passwd, it will be helpful to those users.

**Comment by zhouzhen1** [comment]
Can we get this merged? The patch is basically a very small change just to allow ways other than basic auth for authentication. Although it's possible for me to maintain an patched version in our company, in the long term it's very inconvenient, and fragile in terms of staff turnover.

**Comment by frimicc** [comment]
I apologize for the unacceptable delay. This patch has been merged and posted to CPAN. Thanks for your help!

**Pull request merged**
